ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tds_data JSONB;

UPDATE products SET coverage_rate='60-65 sq.ft/litre', warranty_years=15, tds_data='{"type":"Premium Exterior","durability":"15 yrs","dil_brush":"20-25%","dil_roller":"10-15%","dil_spray":"35-40%","drying":"30min-1hr","overcoat":"4-6hrs","coats":"2","voc":"<30ppm"}'::jsonb WHERE code='AZ-EXT-001';
UPDATE products SET coverage_rate='150-175 sq.ft/litre', warranty_years=8, tds_data='{"type":"Pearl Glow Interior","durability":"7-8 yrs","dil_brush":"25-35%","dil_roller":"15-30%","dil_spray":"40-50%","drying":"1hr","overcoat":"4-5hrs","coats":"2-3","voc":"<30ppm"}'::jsonb WHERE code='AZ-INT-002';
UPDATE products SET coverage_rate='125-150 sq.ft/litre', warranty_years=6, tds_data='{"type":"High Sheen Interior","durability":"5+1 yrs","dil_brush":"25-35%","dil_roller":"15-25%","dil_spray":"40-45%","drying":"1hr","overcoat":"4-5hrs","coats":"2","voc":"<30ppm"}'::jsonb WHERE code='AS-INT-001';
UPDATE products SET coverage_rate='60-65 sq.ft/litre', warranty_years=6, tds_data='{"type":"Premium Exterior","durability":"5+1 yrs","dil_brush":"20-25%","dil_roller":"10-15%","dil_spray":"40-50%","drying":"1hr","overcoat":"4-5hrs","coats":"2","voc":"<30ppm"}'::jsonb WHERE code='AS-EXT-001';
UPDATE products SET coverage_rate='125-150 sq.ft/litre', warranty_years=6, tds_data='{"type":"Advance Interior","durability":"5+1 yrs","dil_brush":"25-30%","dil_roller":"15-20%","dil_spray":"45%","drying":"1hr","overcoat":"4-5hrs","coats":"2","voc":"<40ppm"}'::jsonb WHERE code='AN-INT-001';
UPDATE products SET coverage_rate='65-75 sq.ft/litre', warranty_years=4, tds_data='{"type":"Economy Exterior","durability":"3+1 yrs","dil_brush":"25-35%","dil_roller":"10-15%","dil_spray":"40-45%","drying":"1hr","overcoat":"4-5hrs","coats":"2","voc":"<40ppm"}'::jsonb WHERE code='AN-EXT-001';
UPDATE products SET coverage_rate='120-140 sq.ft/litre', warranty_years=5, tds_data='{"type":"Economy Interior","durability":"4-5 yrs","dil_brush":"25-35%","dil_roller":"15-25%","dil_spray":"40-45%","drying":"1hr","overcoat":"4-5hrs","coats":"2-3","voc":"<40ppm"}'::jsonb WHERE code='AT-INT-001';
UPDATE products SET coverage_rate='65-75 sq.ft/litre', warranty_years=4, tds_data='{"type":"Economy Exterior","durability":"3+1 yrs","dil_brush":"25-35%","dil_roller":"10-15%","dil_spray":"40-45%","drying":"1hr","overcoat":"4-5hrs","coats":"2","voc":"<40ppm"}'::jsonb WHERE code='AT-EXT-001';
UPDATE products SET coverage_rate='90-95 sq.ft/litre per coat', warranty_years=10, tds_data='{"type":"Dual Primer","durability":"10 yrs","dil_brush":"35-45%","dil_spray":"50-55%","drying":"1hr","overcoat":"4-5hrs","coats":"1-2","voc":"<30ppm"}'::jsonb WHERE code='AZ-PRM-001';
UPDATE products SET coverage_rate='150-180 sq.ft/litre per coat', warranty_years=6, tds_data='{"type":"Universal Primer","durability":"5+1 yrs","dil_brush":"40-45%","dil_spray":"60-70%","drying":"1hr","overcoat":"4-5hrs","coats":"1-2","voc":"<30ppm"}'::jsonb WHERE code='AM-PRM-002';
UPDATE products SET coverage_rate='24-25 sq.ft/litre', warranty_years=12, tds_data='{"type":"PU Waterproof RoofCoat","durability":"12+ Yrs","dil_brush":"15-20%","dil_roller":"10-15%","dil_spray":"30-35%","drying":"1hr","overcoat":"4-6hrs","coats":"2","voc":"<30ppm"}'::jsonb WHERE code='AR-WP-002';
UPDATE products SET coverage_rate='50-55 sq.ft/Ltr', warranty_years=10, tds_data='{"type":"Flexible Base Coat","durability":"10 Yrs","voc":"<30ppm"}'::jsonb WHERE code='AR-WP-001';
UPDATE products SET coverage_rate='85-107 sq.ft/ltr', warranty_years=5, tds_data='{"type":"Metallica Gold Silver","durability":"5 yrs","drying":"1hr","overcoat":"6-8hrs","coats":"2-3","voc":"<30ppm"}'::jsonb WHERE code='MT-INT-001';
UPDATE products SET coverage_rate='95-120 sq.ft/litre', warranty_years=4, tds_data='{"type":"Hi-Gloss Enamel","durability":"4+ yrs","dil_brush":"5% Thinner","dil_spray":"10-15% Thinner","drying":"2.5hrs","overcoat":"6-8hrs","coats":"2-3"}'::jsonb WHERE code='AP-EN-001';

SELECT 'TDS updated' AS status;