'use client';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Calendar, Clock, ArrowRight } from 'lucide-react';

const posts: Record<string, any> = {
  'clear-protective-water-based-topcoat': {
    title: 'Clear Water-Based Topcoats: Protection Without Changing the Look',
    date: '20 August 2026', readTime: '7 min read', category: 'Technology',
    image: '/img/heroes/hero-technical-library.jpg',
    content: [
      'There are surfaces you want to protect without hiding: exposed brickwork, natural stone, architectural concrete, signage, a feature wall that has been finished at some expense. A clear coat is the obvious answer, and it is also the hardest kind of coating to make work.',
      'The reason is pigment. In a normal coating the pigment does more than provide colour — it absorbs and scatters ultraviolet light before that light can reach the resin binder. Remove the pigment and the UV goes straight through to the binder, which is the part that degrades. A clear coat is a coating with its own UV shield deliberately taken out.',
      '## What a clear coat is actually being asked to do',
      '**Let the substrate show through.** Any yellowing, milkiness or gloss change is immediately visible, because there is nothing to hide behind.',
      '**Resist UV without pigment.** This is done with UV absorbers and hindered amine light stabilisers in the formulation, and with a resin that is inherently UV stable. Aliphatic chemistry is stable; aromatic chemistry yellows.',
      '**Stay breathable on masonry.** Brick, stone and concrete hold moisture and need to release it. A clear coat that seals the surface completely will trap moisture behind the film, and on masonry that means blistering, or worse, freeze damage and spalling in colder regions.',
      '**Not darken the substrate.** Many clear coatings wet the surface optically and leave it looking permanently damp. On natural stone that is often unacceptable.',
      '## Why water-based matters here',
      'Solvent-borne clear coats have been available for decades and still perform well in some applications. Water-based clear technology has closed most of the performance gap and brings advantages that matter on occupied buildings.',
      '**Low VOC.** Applying a solvent-borne clear inside a working building means evacuating the area, managing vapour and dealing with odour complaints for days. Water-based systems can be applied with the space in use.',
      '**Lower fire risk during application.** Relevant in occupied premises and mandatory in some plant environments.',
      '**Vapour permeability.** Water-based acrylic and polyurethane dispersion clears can be formulated to remain breathable, which is exactly what masonry needs.',
      '**Easier equipment cleaning,** which in practice means applicators actually clean their equipment, which in turn means fewer defects on the next job.',
      '## Where clear coats belong',
      '**Exposed brick and stone elevations.** Protection against water ingress, staining and biological growth while keeping the appearance.',
      '**Architectural concrete.** Fair-faced concrete is expensive to get right and easy to ruin with staining. A breathable clear protects it.',
      '**Anti-graffiti applications.** A sacrificial or permanent clear allows paint to be removed without damaging what is underneath. This is worth specifying on any accessible pier, underpass or boundary wall in an urban location.',
      '**Over decorative finishes** that need mechanical protection — a textured or metallic finish in a high-traffic corridor.',
      '**Sealing photoluminescent marking,** where the seal must be non-yellowing or the glow performance drops over time.',
      '## Where they fail, and why',
      '**Applied too thick.** Clear coats show every application defect. Runs, sags and lap marks that a pigmented coating would hide are permanently visible. Thin, even coats applied with discipline.',
      '**Applied over a damp substrate.** Moisture trapped under a clear film produces a milky bloom that cannot be corrected without removing the coating.',
      '**Used on an unsound surface.** A clear coat is not a repair. Applied over friable or chalking masonry it will lift and take the surface with it.',
      '**Expected to last as long as a pigmented system.** Even the best clear coat has a shorter maintenance cycle than an equivalent pigmented one. Plan for it rather than being surprised by it.',
      '## Questions worth asking before specifying one',
      '1. Is the resin aliphatic? Aromatic polyurethane will yellow, and on a clear coat that is a visible failure rather than a technical one.',
      '2. What is the water vapour transmission rate? On masonry this decides whether the wall can still dry.',
      '3. Does it darken the substrate? Ask for a sample panel on the actual material, not a photograph.',
      '4. Is it sacrificial or permanent, if the purpose is anti-graffiti? The removal method differs completely.',
      '5. What is the expected maintenance interval in this exposure? A clear coat on a south-facing elevation and one in a sheltered courtyard are different propositions.',
      '## The practical summary',
      'Specify a clear coat when the appearance of the substrate is the point, and accept that you are trading some durability for that. Insist on a sample panel on the real material before committing — with clear coatings, more than any other type, the only reliable test is seeing it on the actual surface in the actual light.',
    ],
  },
  'super-hydrophobic-coatings-what-they-do': {
    title: 'Super-Hydrophobic Coatings: Separating the Physics from the Marketing',
    date: '18 August 2026', readTime: '8 min read', category: 'Technology',
    image: '/img/heroes/hero-product-range.jpg',
    content: [
      'Few coating technologies demonstrate as well as a super-hydrophobic surface. Water lands, forms near-perfect spheres, and rolls off carrying dust with it. It looks like a solved problem.',
      'The physics is real and useful. The question worth asking is a different one: how long does the effect last on a wall exposed to Indian summer, monsoon and urban pollution, and is it the right way to spend the money?',
      '## What hydrophobic actually means',
      'The measure is **contact angle** — the angle a water droplet makes where it meets the surface.',
      'Below 90 degrees the surface is hydrophilic and water spreads. Above 90 degrees it is hydrophobic and water beads. Above roughly 150 degrees, with a low roll-off angle, the surface is described as super-hydrophobic and droplets barely touch it at all.',
      'Ordinary exterior emulsion sits somewhere around 70 to 90 degrees. A silicone modified exterior coating typically reaches 100 to 110. Reaching 150 requires more than chemistry — it requires **surface texture at the microscopic scale**, which is what allows air to remain trapped beneath the droplet so that the water is resting largely on air rather than on the coating.',
      'That last point is the whole story, and it is where the honest discussion begins.',
      '## Why the effect degrades',
      'Super-hydrophobicity depends on a delicate micro-texture. Anything that fills, flattens or contaminates that texture reduces the effect.',
      '**Dust and pollution** settle into the micro-structure. In an Indian urban environment that begins within weeks.',
      '**Abrasion** flattens the texture. Rain, wind-borne sand and any cleaning all take a toll.',
      '**Oil and organic contamination** from vehicle exhaust bridge the texture and destroy the air layer locally.',
      '**UV degradation** of the surface chemistry reduces the low surface energy that the effect also depends on.',
      'A laboratory panel holding 155 degrees on day one may be at 110 to 120 degrees after a year outdoors — still genuinely water repellent, and still useful, but no longer super-hydrophobic. Any supplier quoting a contact angle should be asked for the figure after weathering, not on a fresh panel.',
      '## Where the technology genuinely earns its place',
      '**Facade water repellency.** Reducing water absorption into masonry reduces efflorescence, biological growth and thermal loss. A durable hydrophobic treatment does this well, and it does not need to reach 150 degrees to do it.',
      '**Reduced dirt pickup.** Water rolling off carries loose dust with it. On an exterior elevation in a dusty city this is the difference between a building looking maintained and looking neglected at year three.',
      '**Anti-algal performance.** Algae and fungus need persistent surface moisture. A surface that sheds water dries faster and stays cleaner, which matters enormously on north-facing and shaded elevations in humid regions.',
      '**Protecting porous stone** where a film-forming coating would be visually unacceptable. A penetrating hydrophobic treatment leaves the appearance unchanged.',
      '## Where it is oversold',
      '**As a waterproofing system.** A hydrophobic surface repels water landing on it. It does not bridge cracks, it does not resist standing water, and it will not stop seepage through a terrace. Waterproofing needs an elastomeric membrane with crack-bridging capability, applied to the right side of the structure.',
      '**As permanently self-cleaning.** Self-cleaning works for loose particulate. It does not remove bonded soiling, oily grime or biological staining, and the effect diminishes as the surface weathers.',
      '**On horizontal surfaces.** The rolling action needs a slope. On a flat roof, water sits regardless of contact angle.',
      '**As a substitute for surface preparation.** Applied over a chalking or damp wall, a hydrophobic coating fails as quickly as any other.',
      '## What to specify instead of a contact angle number',
      'Contact angle on a fresh panel is easy to achieve and tells you little. These are more useful:',
      '1. **Water absorption to EN 1062-3.** A direct measure of how much water the coated surface actually takes up.',
      '2. **Water vapour permeability to EN ISO 7783.** Critical on masonry — the wall must still be able to dry outward. A coating that repels liquid water but also blocks vapour will trap moisture inside the wall.',
      '3. **Contact angle after accelerated weathering,** not before.',
      '4. **Dirt pickup resistance after twelve months** of real exposure, ideally on a reference building you can visit.',
      '5. **Anti-algal performance to ASTM D3273** for humid and shaded locations.',
      'The combination of low water absorption and high vapour permeability is what actually protects a wall. It is less photogenic than a beading video and considerably more predictable.',
      '## The practical view',
      'Water repellency is a genuinely valuable property, particularly in the Indian climate where wind-driven rain, humidity and dust all attack elevations at once. Treat super-hydrophobicity as the top of a spectrum rather than a category of its own, ask for weathered performance figures, and be clear about what it is not — which is a waterproofing system.',
    ],
  },
  'pu-waterproofing-terrace-arest-system': {
    title: 'PU Waterproofing for Terraces: Why Elastomeric Beats Rigid Every Time',
    date: '16 August 2026', readTime: '8 min read', category: 'Waterproofing',
    image: '/img/app/decorative/dec-roof-waterproof.jpg',
    content: [
      'Ask any building manager in eastern India what fails first and the terrace will be near the top of the list. Ask what specifically failed, and the answer is almost never the middle of the slab. It is a crack, a parapet junction, a drain outlet or the point where a pipe passes through.',
      'That pattern tells you what a terrace waterproofing system actually has to do. It is not primarily about resisting water on a flat surface. It is about accommodating movement without opening a path for water.',
      '## Why terraces move',
      'A concrete terrace in India is subjected to a daily thermal cycle that few structures anywhere face. A dark roof surface can reach 60 to 70 degrees Celsius in the afternoon and fall to near ambient overnight. Concrete expands and contracts with that cycle, every day, for the life of the building.',
      'Add structural settlement, shrinkage of the screed in the first year, and vibration, and the result is a surface that is constantly working. Any waterproofing layer that cannot move with it will crack — and a cracked waterproofing layer is not waterproofing at all.',
      '## Rigid versus elastomeric',
      '**Cementitious systems** are rigid. Polymer-modified cementitious coatings bond superbly to concrete, resist water well, and are excellent below tiles in bathrooms where movement is minimal and the covering protects them. On an exposed terrace taking full thermal cycling, a rigid system will eventually crack at the points of highest movement.',
      '**Elastomeric polyurethane systems** are designed to stretch. A quality PU membrane will accommodate substantial elongation before failure and, more importantly, will bridge a crack that opens beneath it rather than transmitting it through the film.',
      '**Bituminous membranes** have their place, particularly on large flat roofs, but sheet systems introduce laps and joints — and laps are where sheet systems fail. They also perform poorly under sustained UV unless protected.',
      'For an exposed Indian terrace, the elastomeric liquid-applied route makes the most sense: no joints, conformable to every detail, and capable of moving with the structure.',
      '## Crack bridging is the specification that matters',
      'This is the property to ask about, and it is measured. EN 1062-7 classifies crack bridging ability, with tests carried out at low temperature where materials are least flexible.',
      'A system quoting high elongation at 25 degrees but nothing at low temperature is telling you only half the story. It is also worth asking about elongation **after ageing** — many materials become progressively less flexible with UV exposure, so the crack-bridging figure that matters is the one at year five, not year one.',
      '## The sequence that actually works',
      '**One — find and fix the source.** If water is already entering, the terrace membrane may not be the whole problem. Check parapet copings, drain outlets, plumbing penetrations and the junction with adjacent structures.',
      '**Two — prepare the surface properly.** Remove laitance and loose material. The substrate must be sound, clean and dry. Moisture in the slab under an impermeable membrane produces blisters within a season.',
      '**Three — treat the details first.** Cracks opened out and filled. Coves formed at every wall junction — a sharp internal angle is where the membrane thins and splits. Reinforcing tape or fabric at all junctions, drains and penetrations. This step takes the longest and prevents the most failures.',
      '**Four — apply the base coat** and let it cure properly. Rushing between coats traps solvent and moisture.',
      '**Five — apply the membrane** to the specified thickness, in the specified number of coats. Terrace waterproofing is one place where dry film thickness is directly proportional to service life, and thinning to stretch material across a larger area is a false economy that shows up in three years.',
      '**Six — pond test before handover.** Flood the terrace, leave it 48 hours, inspect the ceiling below. Do this before anything is laid over the membrane. After tiling, a failure is a demolition job.',
      '## Combining waterproofing with heat reflection',
      'A well-chosen terrace system can do two jobs. A light-coloured, high-reflectance elastomeric topcoat waterproofs and simultaneously lowers the roof surface temperature.',
      'The thermal benefit is real, and there is a second-order benefit that is less obvious: a cooler roof cycles through a narrower temperature range, which means less daily movement, which means less stress on the waterproofing itself. The reflective finish extends the life of the membrane beneath it.',
      '## What to ask a supplier',
      '1. Crack bridging classification to EN 1062-7, including the test temperature',
      '2. Elongation after accelerated weathering, not just on a fresh sample',
      '3. Total dry film thickness required, and the number of coats to reach it',
      '4. Detailing requirements at coves, drains and penetrations, in writing',
      '5. Solar reflectance if a reflective finish is part of the system',
      '6. A reference terrace you can visit that is at least three monsoons old',
      'That last one is worth more than the first five. Any system looks good in year one.',
    ],
  },
  'heat-reflective-coatings-buildings-india': {
    title: 'Heat Reflective Coatings: What the Numbers Mean and What They Are Worth',
    date: '14 August 2026', readTime: '7 min read', category: 'Technology',
    image: '/img/heroes/hero-home-painting.jpg',
    content: [
      'Indian summers have lengthened and intensified, and the roof is where most of that heat enters a building. Reflective roof coatings have moved accordingly, from a specialty product to something specified routinely on warehouses, factory sheds, top-floor apartments and cold storage.',
      'The technology works. The claims made for it range from carefully measured to wildly optimistic, and the difference between the two comes down to understanding which temperature is being quoted.',
      '## Two properties, one result',
      '**Solar reflectance** is the fraction of incoming solar energy the surface bounces back rather than absorbing. A dark bitumen roof might reflect under ten percent. A quality white reflective coating can reflect eighty percent or more.',
      '**Thermal emittance** is how readily the surface radiates absorbed heat back out. A good reflective coating scores high on both: it takes in less energy, and it sheds what it does take in.',
      'The two are often combined into the **Solar Reflectance Index**, and SRI is the single most useful number to ask for. It is measured to ASTM E1980 and it lets you compare products directly.',
      '## The number that gets misquoted',
      'Here is where most confusion comes from. Two very different figures are both described as temperature reduction.',
      '**Surface temperature reduction** is large and easy to demonstrate. An uncoated concrete or metal roof in peak Indian summer can reach 60 to 70 degrees Celsius. A well-applied reflective coating typically brings that surface down by 15 to 25 degrees. Point an infrared thermometer at a half-coated roof and the difference is dramatic and genuine.',
      '**Indoor air temperature reduction** is what the building owner actually cares about, and it is far smaller — usually 3 to 6 degrees in an uninsulated single-storey structure directly beneath the coated roof.',
      'Both figures are true. They measure different things. A supplier quoting a large indoor reduction is either quoting the surface figure or is not measuring carefully, and it is a fair question to ask which one they mean.',
      '## Where the payback is strongest',
      'Reflective coatings deliver most where the roof is the dominant heat path into the occupied space.',
      '**Single-storey industrial sheds and warehouses,** particularly metal-roofed, where a large roof area sits directly over the working floor and there is no insulation.',
      '**Top-floor apartments,** which routinely run several degrees hotter than the floors below and where the occupant pays the cooling bill.',
      '**Cold storage and temperature-controlled facilities,** where every degree of heat gain is paid for continuously in compressor load. The payback here is usually the fastest of any application.',
      '**Buildings with no roof insulation** — which describes most of the existing Indian building stock.',
      'They deliver least on multi-storey buildings with a small roof-to-floor-area ratio, on already well-insulated roofs, and where the roof is shaded by adjacent structures.',
      '## The three things that decide whether it works',
      '**Film thickness.** Reflectance depends on an opaque, continuous film. A coating applied thin, or in fewer coats than specified to stretch the material, will not reflect as claimed. This is the single most common reason for underperformance and it is entirely avoidable.',
      '**Dirt retention.** Reflectance falls as the surface soils. A white roof that has gone grey has lost a substantial part of its benefit. Products differ significantly in resistance to this, and the honest measure is reflectance after three years of weathering rather than on day one. Periodic washing restores most of the loss, and on a large roof that is a cheap intervention.',
      '**Substrate condition.** A reflective coating over a cracked or leaking roof is a cosmetic exercise. Most quality systems combine waterproofing with reflectivity for exactly this reason — the film has to stay continuous to do either job.',
      '## Reflective coating is not insulation',
      'This distinction gets blurred and it matters commercially. A reflective coating reduces the heat **entering** the roof. Insulation slows the heat **passing through** it. They address different parts of the same problem and work well together.',
      'For a building with a severe thermal load, insulation plus a reflective coating will outperform either alone. For an existing building where retrofitting insulation is disruptive and expensive, a reflective coating is the pragmatic intervention — applied in days, with no structural work and no shutdown.',
      '## Doing the calculation for your building',
      'A reasonable estimate needs four inputs: roof area, whether the roof is insulated, the cooling load or electricity spend attributable to the top floor, and the local tariff. Multiply through and most uninsulated single-storey industrial buildings in Indian conditions show a payback measured in a small number of cooling seasons, before counting the comfort and productivity benefit of a cooler working floor.',
      'It is worth asking any supplier to do that calculation with you using your numbers, rather than quoting a generic percentage saving. If they will not, that in itself is informative.',
    ],
  },
  'india-paint-price-war-2026-what-project-buyers-should-know': {
    title: 'India\'s Paint Price War: What Project Buyers Should Actually Watch',
    date: '4 August 2026', readTime: '6 min read', category: 'Industry',
    image: '/img/heroes/hero-oil-gas.jpg',
    content: [
      'India\'s decorative paint market has spent the past two years in the most competitive phase of its history. Aditya Birla\'s entry with Birla Opus, backed by an investment of around ₹10,000 crore, added enormous capacity to a market that had been an effective oligopoly for decades. JSW Paints has pushed in the same direction. Discounting followed, dealer incentives escalated, and the incumbents responded.',
      'If you buy paint for a home, this is straightforwardly good news. If you buy coatings for a project, the picture is more complicated — and reading the decorative headlines as a guide to industrial pricing will mislead you.',
      '## Decorative and protective coatings are different businesses',
      'A litre of interior emulsion and a litre of glass flake epoxy share a category name and almost nothing else. Decorative paint competes on brand, shade range, dealer reach and retail shelf presence. Its cost base is dominated by titanium dioxide, acrylic emulsion and packaging, and its buyer usually decides in a shop.',
      'Protective coatings compete on specification compliance, approval status, technical service and delivered performance over fifteen to twenty-five years. The cost base runs on epoxy resin, isocyanates, zinc dust, and specialty pigments — most of them petrochemical derivatives or imported metals. The buyer is an engineer working to a written specification.',
      'Capacity added for decorative emulsion does not produce zinc-rich primer. So the price war has had far less effect on the industrial segment than the coverage suggests.',
      '## What genuinely moves industrial coating prices',
      '**Crude oil and petrochemical feedstock.** Epoxy resins, polyurethane hardeners and most solvents trace back to crude. When oil moves sharply, protective coating costs follow within a quarter or two.',
      '**Titanium dioxide.** Global TiO₂ pricing affects every white and light-toned coating regardless of segment.',
      '**Zinc.** Zinc-rich primers to SSPC-Paint 20 carry a high metallic zinc loading. Zinc is an exchange-traded metal, and its price passes directly into primer cost.',
      '**Currency.** A large share of raw material is imported. Rupee movement against the dollar is a real input.',
      '**Freight and geopolitics.** Supply routes for specialty raw materials have been disrupted repeatedly in recent years. Availability, not just price, becomes the constraint.',
      '## The mistake worth avoiding',
      'Project buyers under margin pressure often try to capture savings by reducing the coating specification — dropping a coat, thinning the intermediate, substituting a cheaper primer generic. On a structural steel package, coating is typically a low single-digit share of total project cost. Repainting that steel in year eight instead of year twenty is not a low single-digit cost. It involves access, scaffolding, surface preparation, containment, production downtime, and often work at height in an operating facility.',
      'The saving is real and immediate. The cost is larger and arrives later, which is precisely why the trade keeps being made.',
      '## Where a genuine cost advantage comes from',
      'Not every price difference is a quality difference. A manufacturer can be structurally cheaper for reasons that have nothing to do with the film on the steel:',
      '**Backward integration.** Producing your own resin removes a margin layer and stabilises supply.',
      '**Lower overhead.** A national advertising budget and a large distribution network are recovered in the price of every litre sold.',
      '**Direct supply.** Selling into a project without intermediate distribution removes another layer.',
      '**Regional manufacturing.** Freight on a bulky, heavy product is not trivial.',
      'These are the reasons a well-run regional manufacturer can quote ten to fifteen percent below a national brand on the same specification, with the same test data, and the same approvals. It is worth asking any supplier to explain where their price advantage comes from. If the answer is a structural one, the saving is durable. If there is no answer, the saving is probably coming out of the film thickness.',
      '## The practical checklist',
      'When comparing quotations, normalise them before comparing rupees:',
      '1. Compare cost per square metre at specified DFT, not cost per litre.',
      '2. Confirm volume solids — a coating with 50% volume solids delivers half the dry film per litre of one at 100%.',
      '3. Check the approval status actually required by your client, not approvals in general.',
      '4. Ask for batch test certificates, not a generic product data sheet.',
      '5. Confirm technical service at site is included, and what it means in practice.',
      'A cheaper quotation that meets the specification is a saving. A cheaper quotation that quietly changes the specification is a deferred cost.',
    ],
  },
  'low-voc-coatings-india-regulation-green-building': {
    title: 'Low-VOC Coatings in India: What Regulation and Green Building Now Expect',
    date: '21 July 2026', readTime: '7 min read', category: 'Sustainability',
    image: '/img/heroes/hero-approvals.jpg',
    content: [
      'Volatile organic compounds have moved from a footnote in the technical data sheet to a determining factor in whether a product can be specified at all. For anyone writing coating specifications in India, the direction of travel is clear even where the enforcement is uneven.',
      '## What a VOC actually is',
      'Volatile organic compounds are carbon-based solvents that evaporate at room temperature. In a coating they perform a real function: they reduce viscosity so the material can be applied, then leave the film as it dries. That evaporation is the smell of fresh paint, and it is also the problem. VOCs contribute to ground-level ozone, degrade indoor air quality, and in enclosed spaces present a genuine occupational exposure risk during application.',
      'VOC content is normally expressed in grams per litre. A conventional solvent-borne alkyd enamel might sit in the hundreds. A modern water-borne interior emulsion can be under fifty, and solvent-free epoxy systems approach zero.',
      '## The regulatory direction',
      'The Bureau of Indian Standards and the Central Pollution Control Board have both been tightening expectations around VOC content and manufacturing emissions. The practical effect on formulators has been a steady shift toward water-borne chemistry in architectural coatings, and toward high-solids and solvent-free chemistry in industrial ones.',
      'This matters commercially as well as environmentally. A manufacturer that has already reformulated is not exposed to the next tightening. One that has not will face a reformulation cycle under time pressure, and reformulation is not a paperwork exercise — it changes application behaviour, drying, and sometimes performance.',
      '## Green building rating and the documentation problem',
      'IGBC, GRIHA and LEED all award credits for low-emitting materials. The credit is not awarded for a manufacturer being broadly environmentally minded. It is awarded on evidence, and the evidence has to be product-specific.',
      'This is where most projects lose time. The green building consultant asks for VOC content per product, with test method and a declaration on letterhead. What arrives is a marketing brochure describing the range as eco-friendly. The credit cannot be documented from that.',
      'If you are specifying for a rated project, ask for the following before the product is approved, not after:',
      'VOC content in g/L for the exact product and shade family',
      'The test method used to determine it',
      'A signed declaration referencing the batch or product code',
      'Confirmation of any heavy metal content restrictions the rating system imposes',
      '## Low-VOC does not mean lower performance',
      'There is a persistent belief in the market that water-borne and low-VOC systems underperform their solvent-borne equivalents. Twenty years ago there was substance to it. Today it depends entirely on the specific product.',
      'Modern water-borne acrylic exteriors offer excellent UV and colour retention. Water-borne epoxies are established for interior industrial floors and walls. High-solids epoxy delivers greater film build per coat than the conventional material it replaced, which often means fewer coats and less labour.',
      'There remain applications where solvent-borne chemistry is still the right technical answer — certain immersion services, some low-temperature applications, particular chemical resistance requirements. The correct response is to select on the requirement rather than on principle in either direction.',
      '## The application-side consequences',
      'Switching to low-VOC systems changes site practice, and this is where projects are most often caught out:',
      '**Drying is humidity-sensitive.** Water-borne coatings dry by water evaporation. In high humidity — which describes much of coastal and eastern India for months at a time — drying slows considerably. Recoat intervals from the data sheet assume stated conditions.',
      '**Surface preparation matters more, not less.** Water-borne materials are less tolerant of oily or contaminated substrates than the solvent-borne systems they replace.',
      '**Storage and freezing.** Water-borne products have a minimum storage temperature. This is rarely an issue in most of India, but it matters in northern winter conditions.',
      '**Equipment.** Application equipment and cleaning regimes differ. Contamination from previous solvent-borne work causes defects.',
      '## What to ask your supplier',
      'The useful questions are specific:',
      '1. What is the VOC content of this product in g/L, by what test method?',
      '2. Is a product-level declaration available for green building documentation?',
      '3. What is the recoat window at 30°C and 80% relative humidity, not at laboratory conditions?',
      '4. Has this product been used on a rated project, and can that be referenced?',
      'A supplier who can answer those four quickly has done the work. One who redirects to a general sustainability statement has not.',
    ],
  },
  'heat-reflective-roof-coatings-india-summer-temperatures': {
    title: 'Heat-Reflective Roof Coatings: Real Numbers Behind the Cooling Claim',
    date: '8 July 2026', readTime: '6 min read', category: 'Technology',
    image: '/img/heroes/hero-industrial-flooring.jpg',
    content: [
      'Indian summers have grown longer and hotter, and the consequences show up in electricity bills, in worker productivity inside sheds and factories, and in the service life of the roof itself. Heat-reflective coatings have moved accordingly — from a specialty product to something specified routinely on warehouses, factory sheds and residential terraces.',
      'The claims made for them range from the credible to the fanciful. It is worth separating the two.',
      '## The physics, briefly',
      'A roof surface heats up because it absorbs solar radiation. How much it absorbs depends on two properties:',
      '**Solar reflectance** — the fraction of incoming solar energy the surface reflects rather than absorbs. A dark bitumen roof might reflect under ten percent. A white reflective coating can reflect eighty percent or more.',
      '**Thermal emittance** — how readily the surface radiates absorbed heat back out. A good reflective coating scores high on both, so it takes in less energy and sheds what it does take in.',
      'The combination is sometimes expressed as the Solar Reflectance Index. Higher is better, and it is the number worth asking for.',
      '## What temperature reduction is realistic',
      'Here is where marketing and measurement diverge. Two quite different figures get quoted, and they are not comparable.',
      '**Surface temperature reduction** is large and easy to demonstrate. An uncoated concrete or metal roof in peak Indian summer can reach 60–70°C. A well-applied reflective coating can bring that surface down by 15–25°C. Point an infrared thermometer at a half-coated roof and the difference is dramatic.',
      '**Indoor air temperature reduction** is what the building owner actually cares about, and it is much smaller — typically 3–6°C in an uninsulated single-storey structure under a coated roof. That is a genuinely useful reduction, but it is not the number on the banner.',
      'Any supplier quoting a large indoor temperature drop is either quoting the surface figure or is not measuring carefully. Ask which one they mean.',
      '## Where the payback is strongest',
      'Reflective coatings deliver most where the roof is the dominant heat path into the building:',
      '**Single-storey industrial sheds and warehouses**, particularly metal-roofed, where a large roof area sits directly over the occupied space',
      '**Top-floor apartments**, which routinely run several degrees hotter than the floors below',
      '**Cold storage and temperature-controlled facilities**, where every degree of heat gain is paid for in compressor load',
      '**Buildings with no roof insulation**, which is most of the existing Indian building stock',
      'They deliver least on multi-storey buildings with small roof-to-floor ratios, on already well-insulated roofs, and on roofs heavily shaded by adjacent structures.',
      '## The three things that determine whether it works',
      '**Application thickness.** Reflectance depends on an opaque, continuous film. A coating applied thin, or in fewer coats than specified to save material, will not reflect as claimed. This is the single most common reason for underperformance.',
      '**Dirt retention.** Reflectance falls as the surface soils. A white roof that has gone grey has lost a substantial part of its benefit. Products differ significantly in how well they resist this, and the honest measure is reflectance after three years of weathering, not on day one. Periodic washing restores much of the loss.',
      '**Substrate condition and waterproofing.** A reflective coating applied over a cracked or leaking roof is a cosmetic exercise. Most quality systems combine waterproofing and reflectivity for exactly this reason — the coating has to remain a continuous film to do either job.',
      '## Reflective coating is not insulation',
      'This distinction gets blurred and it matters. A reflective coating reduces the heat *entering* the roof. Insulation slows the heat *passing through* it. They address different parts of the same problem and work well together.',
      'For a building with a genuinely severe thermal load, insulation plus a reflective coating will outperform either alone. For an existing building where retrofitting insulation is disruptive and expensive, a reflective coating is often the pragmatic intervention — applied in days, with no structural work.',
      '## Questions worth asking',
      '1. What is the solar reflectance, and by what test method?',
      '2. What is the reflectance after three years of weathering?',
      '3. Is the temperature figure quoted a surface or an indoor air measurement?',
      '4. What total dry film thickness is required to achieve the stated reflectance?',
      '5. Does the product also provide waterproofing, and what is the crack-bridging capability?',
      'The first and third questions separate a measured product from a marketed one.',
    ],
  },
  'monsoon-damp-seepage-exterior-walls-eastern-india': {
    title: 'Why Walls Fail in the Monsoon — and What Actually Fixes Them',
    date: '24 June 2026', readTime: '8 min read', category: 'Home Painting',
    image: '/img/heroes/hero-home-painting.jpg',
    content: [
      'Every year after the monsoon, the same complaint arrives: the wall was painted eighteen months ago with a good quality product, and now there are damp patches, the paint is lifting, and there is white powder along the skirting.',
      'The instinct is to blame the paint. Occasionally that is fair. Far more often the paint is a casualty rather than the culprit, and repainting without addressing the cause simply resets the clock on the same failure.',
      '## Read the symptom before choosing the remedy',
      'Different failures look superficially similar and have entirely different causes.',
      '**Efflorescence** — white crystalline powder on the surface. Water has moved through the masonry, dissolved salts, carried them to the surface and evaporated, leaving the salt behind. The presence of efflorescence is proof that water is moving through the wall.',
      '**Blistering** — dome-shaped bubbles in the paint film. Moisture behind the film has vaporised and pushed it away from the substrate. It indicates the wall was damp when painted, or has become damp since.',
      '**Peeling and flaking** — the coating detaching in sheets. Usually an adhesion failure: paint applied over a chalky, dusty, damp or previously unprepared surface.',
      '**Dark patches without lifting** — moisture within the wall showing through a still-intact film. The paint is doing its job; the wall is not.',
      '**Green or black growth** — algae and fungus, which require persistent surface moisture and shade. Common on north-facing walls and anywhere with poor drainage.',
      '## Trace the water first',
      'Damp has a source. Fixing the wall without fixing the source guarantees repetition. In practice the water is usually coming from one of five places:',
      '**Rain penetration through cracks.** Plaster develops hairline cracks with thermal movement. Driven rain enters, and the wall does not dry between spells during monsoon.',
      '**Terrace or roof failure.** Water enters at the top and travels down inside the wall, often appearing several feet from the actual leak. Ceiling damp at a wall junction usually means a roof problem, not a wall problem.',
      '**Rising damp.** Ground moisture drawn up through the foundation by capillary action, typically appearing as a band up to a metre above floor level and often accompanied by efflorescence.',
      '**Plumbing leaks.** A concealed supply or drain line inside the wall. Persistent, sharply localised damp that does not vary with the weather points here.',
      '**Condensation.** Warm humid air meeting a cooler wall surface. Common in bathrooms, kitchens and air-conditioned rooms, and often mistaken for external ingress.',
      'A moisture meter and some patience will usually distinguish these. Damp that worsens within hours of rainfall is external ingress. Damp that persists identically through a dry spell is plumbing or rising damp.',
      '## The sequence that actually works',
      'Once the source is fixed, the repair sequence matters more than the product choice.',
      '**One — stop the water.** Repair terrace waterproofing, seal external cracks, fix the leaking pipe, correct the drainage. Nothing applied to the inner face of a wall will compensate for water still entering the outer face.',
      '**Two — let the wall dry.** This is the step most often skipped, because it takes time and nobody wants to wait. A thoroughly wet masonry wall may need several weeks to dry. Painting a damp wall traps moisture and guarantees blistering, whatever the product.',
      '**Three — remove all failed material.** Scrape back to a sound, firm surface. Every square inch of loose, chalking or poorly adhered coating must go. Wash off salt deposits and treat any biological growth with a proprietary wash rather than water alone, which simply redistributes spores.',
      '**Four — repair the substrate.** Fill cracks with an appropriate filler. Hairline cracks need a flexible crack filler; structural cracks need structural attention, not paint.',
      '**Five — prime correctly.** This is where product selection genuinely matters. A damp-resistant, alkali-blocking primer performs two jobs: it resists residual moisture movement and it neutralises the alkalinity of fresh cement, which otherwise attacks the topcoat. Fibre-reinforced primers add crack-bridging over hairline movement.',
      '**Six — topcoat.** An exterior emulsion formulated for the climate: UV stable, resistant to dirt pickup, and with anti-fungal properties for shaded elevations.',
      '## Why cheap repainting is expensive',
      'A budget repaint over an unaddressed damp problem typically fails within one or two monsoons. Two such cycles cost more in labour alone than doing it correctly once, and the wall is worse each time because each failure leaves the substrate more degraded.',
      'Labour is the majority of the cost of painting a building. Paint is the minority. Optimising the minority while wasting the majority is the wrong economy.',
      '## For high-humidity regions specifically',
      'Kolkata, coastal Odisha, the north-east and similar climates share a punishing combination: extended monsoon, high year-round humidity, and limited drying windows. Some practical adjustments:',
      'Do exterior work in the dry months. A wall painted in August in Bengal has not dried properly, whatever the surface felt like.',
      'Specify anti-fungal exterior products as standard, not as an upgrade.',
      'Treat waterproofing as part of the paint system rather than a separate trade brought in after failure.',
      'Check the dew point before starting. Applying coating to a surface below dew point traps condensation under the film.',
    ],
  },
  'iso-12944-corrosivity-categories-explained': {
    title: 'ISO 12944 in Practice: Choosing the Right Corrosivity Category',
    date: '10 June 2026', readTime: '9 min read', category: 'Technical',
    image: '/img/heroes/hero-technical-library.jpg',
    content: [
      'ISO 12944 is the standard most protective coating specifications in India are written against, directly or indirectly. It is also the standard most often applied loosely — a category chosen by habit or by copying the last project, rather than by assessing the actual environment.',
      'Since the corrosivity category drives the entire system — surface preparation, number of coats, dry film thickness, generic types — getting it wrong sets the wrong specification for the next twenty years.',
      '## The categories',
      'ISO 12944-2 classifies atmospheric environments by corrosivity, measured by the mass loss of standard steel and zinc reference specimens over one year.',
      '**C1 — Very low.** Heated buildings with clean atmospheres. Rarely specified in practice.',
      '**C2 — Low.** Unheated buildings, dry rural atmospheres with low pollution.',
      '**C3 — Medium.** Urban and inland industrial atmospheres with moderate sulphur dioxide. Coastal areas of low salinity. This is where a great deal of Indian inland construction genuinely sits.',
      '**C4 — High.** Industrial areas and coastal areas of moderate salinity. Chemical plants, swimming pools, coastal industrial.',
      '**C5 — Very high.** Split into industrial (high humidity, aggressive atmosphere) and marine (coastal and offshore with high salinity). Much of India\'s coastline sits here.',
      '**CX — Extreme.** Offshore areas with high salinity, subtropical and tropical industrial environments with extreme humidity and aggressive atmosphere. Splash zones.',
      'There are also immersion categories: Im1 fresh water, Im2 sea or brackish water, Im3 buried in soil.',
      '## The classification mistakes that cost money',
      '**Treating "near the coast" as a single condition.** Salinity falls off sharply with distance from the shoreline, but not uniformly — prevailing wind direction matters enormously. A structure two kilometres inland but downwind of the sea can be more aggressive than one at five hundred metres in a sheltered aspect.',
      '**Ignoring the microclimate.** The category describes the general environment. The actual condition on a specific member may be far worse: areas that stay wet, surfaces under a leaking joint, the underside of a bridge deck, crevices where chloride accumulates, the zone next to a cooling tower plume. Corrosion begins where water sits longest.',
      '**Confusing category with durability.** These are independent variables. ISO 12944-1 defines durability ranges to first major maintenance — low up to 7 years, medium 7 to 15, high 15 to 25, very high beyond 25. A C3 environment with very high durability may need a more substantial system than a C4 environment with medium durability. Both variables must be stated.',
      '**Forgetting the durability range is not a warranty.** It is a technical planning expectation for the time to first major maintenance, assuming correct application. It is not a guarantee period, and the standard is explicit about this.',
      '## What each category implies for the system',
      'The pattern is consistent as aggression increases: better surface preparation, more zinc in the primer, more barrier thickness in the intermediate, and a more durable topcoat.',
      'At **C2 and C3**, an epoxy zinc phosphate primer with a polyurethane finish is typically adequate for medium durability, with a micaceous iron oxide intermediate added as durability requirements rise.',
      'At **C4**, zinc-rich primers become the norm and the intermediate coat is no longer optional. Total dry film thickness climbs toward 240–280 microns.',
      'At **C5-M and C5-I**, expect a zinc-rich or inorganic zinc silicate primer, one or two high-build intermediates, and a topcoat chosen for both UV and chemical resistance. Total DFT commonly exceeds 320 microns.',
      'At **CX**, surface preparation moves to Sa 3, soluble salt limits tighten considerably, and glass-flake or high-build mastic intermediates become common. Cyclic ageing testing to ISO 20340 or NORSOK M-501 is usually demanded rather than salt spray alone.',
      'For **immersion**, everything changes: white metal blast, solvent-free chemistry, holiday testing across the full surface, and cathodic disbondment resistance where cathodic protection is present.',
      '## Why salt spray alone is a weak criterion',
      'Purchasers frequently compare products on neutral salt spray hours to ASTM B117. It is a useful production control test and a poor predictor of field life.',
      'Real exposure is cyclic — wet then dry, hot then cool, UV then dark. Constant salt fog reproduces none of that. Cyclic ageing tests like ISO 20340 were developed precisely because continuous salt spray was ranking products in an order that field performance did not confirm. For anything C5 or above, ask for cyclic data.',
      '## The part no specification can control',
      'A coating system correctly specified and badly applied will underperform a modest system applied well. The variables that decide the outcome on site are:',
      'Surface preparation actually achieved, not the standard written',
      'Soluble salt contamination, which is invisible and requires testing',
      'Dry film thickness achieved and verified to SSPC-PA2',
      'Stripe coating of edges, welds and fasteners, where film thickness naturally thins',
      'Application within the stated dew point and humidity limits',
      'Observing overcoating intervals in both directions — too soon traps solvent, too late loses intercoat adhesion',
      'Corrosion begins at edges, welds and fasteners in the overwhelming majority of premature failures. That is not a coating formulation problem. It is a stripe coat that was not applied.',
      '## Practical summary',
      'State four things in every specification, and half the ambiguity disappears: the corrosivity category with the reason for it, the required durability range, the surface preparation standard, and the total dry film thickness with the per-coat schedule. Then verify what was actually achieved rather than what was written.',
    ],
  },
  'coatings-metro-rail-expansion-india': {
    title: 'Coating India\'s Metro Expansion: Specification Lessons from the Field',
    date: '27 May 2026', readTime: '7 min read', category: 'Infrastructure',
    image: '/img/heroes/hero-oil-gas.jpg',
    content: [
      'India is building metro rail at a pace few countries have attempted. Dozens of cities are at some stage of construction, extension or planning, and the pipeline extends well past 2030. For coating manufacturers and applicators this is one of the largest sustained sources of demand in the country.',
      'It is also technically awkward work, because a metro project is not one coating job. It is at least five, executed on the same site under one contract.',
      '## Five distinct coating problems in one project',
      '**Elevated viaduct structural steel.** Long-span steel over roads and waterways, in urban atmospheres with vehicle exhaust and often within reach of coastal air. High durability is demanded because access for maintenance is severely constrained — you cannot close a running viaduct to repaint it easily. This pushes specifications toward C4 or C5 systems with 20 to 25 year durability.',
      '**Concrete piers, segments and stations.** Reinforced concrete, where the dominant deterioration mechanism is not general corrosion but carbonation and chloride ingress reaching the reinforcement. The correct product family is anti-carbonation coatings assessed for CO₂ diffusion resistance, not conventional exterior emulsion.',
      '**Underground stations and tunnels.** Permanently damp, poorly ventilated, with restricted working windows and severe fire and smoke requirements for materials in enclosed public spaces. Low-VOC and often solvent-free systems are mandatory here for occupational reasons alone.',
      '**Rolling stock.** Coach exteriors need long-term gloss and colour retention against UV and repeated cleaning, and interiors must satisfy fire, smoke and toxicity requirements — typically EN 45545 hazard levels for enclosed passenger transport.',
      '**Depot and workshop flooring.** Heavy point loads, hydraulic fluid and oil exposure, and maintenance windows that are measured in hours rather than days.',
      'Treating these as a single package, with one product range applied to all of it, is where specifications go wrong.',
      '## The interfaces are where failures start',
      'The steel-to-concrete interface at bearings and pedestals is a classic problem area. Water collects, dries slowly, and the two substrates need different systems that must nonetheless terminate cleanly against one another.',
      'Bolted and welded connections on viaduct steel are the second. The specification says stripe coat; the site often does not, because it is slow, manual and invisible once the full coat goes on. Nearly every premature viaduct coating failure begins at an edge, a bolt head or a weld.',
      'The third is the boundary between contractors. Structural steel is coated in a fabrication shop under controlled conditions. It is then transported, handled, erected, and welded on site, damaging the coating at every stage. The site touch-up specification — how damage is prepared, what product is used, what film thickness is restored — is frequently underspecified and almost always underexecuted. A shop-applied system to C5 standard with touch-up done casually with a brush and whatever primer is available is no longer a C5 system.',
      '## Access is the economic argument',
      'The reason metro specifications demand high durability is not that the atmosphere is unusually aggressive. It is that maintenance access is expensive and disruptive.',
      'Repainting a viaduct over an operating road requires traffic management, access platforms, containment to prevent debris falling on the public, and night working. The direct coating cost is a small fraction of that exercise. When the cost of access dominates, the correct economic decision is to specify a system that defers the access for as long as possible.',
      'This is the argument that persuades value-engineering discussions when a general appeal to quality does not: not that the better system is better, but that the cheaper system commits the operator to an expensive intervention years earlier.',
      '## Documentation is a deliverable',
      'Metro authorities and their consultants run structured vendor registration and approval processes. Products are not accepted on reputation. What is needed, usually well before award:',
      'Product data sheets with complete technical parameters',
      'Independent test reports against the specified standards',
      'Certificates of relevant approvals and registrations',
      'Reference project lists with contactable clients',
      'Manufacturing capacity and quality system certification',
      'Batch test certificates issued against each supply',
      'Manufacturers who assemble this in advance move quickly when a tender appears. Those who begin assembling it after the tender is floated do not participate in that tender.',
      '## What to specify, briefly',
      'For elevated structural steel in an urban Indian environment: assess honestly between C4 and C5 based on distance from coast and local industry; specify high or very high durability given the access constraint; zinc-rich or inorganic zinc silicate primer; a micaceous iron oxide or high-build epoxy intermediate; and a polyurethane or polysiloxane finish. Specify the stripe coat explicitly, specify the site touch-up procedure explicitly, and specify who verifies dry film thickness and against what standard.',
      'The last two sentences matter more than the product names.',
    ],
  },
  'epoxy-vs-polyaspartic-industrial-flooring-downtime': {
    title: 'Epoxy or Polyaspartic Flooring: The Real Cost Is Downtime',
    date: '13 May 2026', readTime: '6 min read', category: 'Technical',
    image: '/img/heroes/hero-industrial-flooring.jpg',
    content: [
      'Industrial floor coating decisions are usually made on a per-square-foot comparison. For a facility that is running, that is the wrong basis, because the coating is rarely the dominant cost.',
      '## Where the money actually goes',
      'On a typical industrial floor coating project in an operating facility, the cost stack looks roughly like this: material, surface preparation, labour, and lost production. In many plants the fourth item exceeds the other three combined.',
      'A food processing line, a pharmaceutical facility, a logistics warehouse in peak season, an automotive plant — each has a value of daily output that dwarfs the cost of the floor. A system that returns the area to service in one day instead of four is not marginally better. It is a different economic proposition.',
      'This is the lens through which the epoxy versus polyaspartic question should be examined.',
      '## Epoxy: the workhorse',
      'Two-pack epoxy floor systems — self-levelling screeds, coatings and mortars — remain the default for good reasons. They bond excellently to properly prepared concrete, resist a wide range of chemicals, take heavy loads, and build substantial thickness in a single application. Cost per square foot is favourable.',
      'The limitations are equally clear. Epoxy cures slowly, particularly at lower temperatures, and full chemical cure can take several days. It has poor UV stability and will yellow and chalk in daylight, which is cosmetic rather than structural but matters in visible areas. And it is relatively rigid, so it tolerates substrate movement poorly.',
      '## Polyaspartic: speed and light stability',
      'Polyaspartic coatings are a class of aliphatic polyurea. Their defining properties are fast cure, excellent UV stability with no yellowing, high abrasion resistance, and the ability to be applied over a wider temperature range, including conditions where epoxy cure becomes impractical.',
      'The trade-offs are a shorter pot life, which demands disciplined mixing and application, a higher material cost per litre, and lower film build per coat than a self-levelling epoxy screed.',
      '## The combination is usually the answer',
      'In practice the strongest industrial floor systems are hybrid: an epoxy primer for adhesion into the concrete, an epoxy screed or self-levelling layer to build thickness and level the surface economically, and a polyaspartic topcoat for abrasion resistance, UV stability and fast return to service.',
      'This uses each chemistry where it is strongest and puts the expensive material only where it is needed.',
      '## Choosing on the actual constraint',
      '**If the facility can be shut down for a week** and the area sees no daylight, a full epoxy system is likely the most economical choice.',
      '**If the shutdown window is a weekend**, polyaspartic topcoats or a fast-cure hybrid become worth their material premium immediately.',
      '**If the area is exposed to daylight** — loading bays, external ramps, skylit warehouses — the topcoat needs to be aliphatic. An epoxy topcoat will discolour.',
      '**If the concrete is old, cracked or moving**, flexibility and crack-bridging matter more than either chemistry\'s headline properties, and the specification should address the substrate first.',
      '**If chemical spillage is the main hazard**, the specific chemicals govern. Novolac epoxy outperforms both standard epoxy and polyaspartic against strong acids.',
      '## The failure nobody budgets for',
      'Whatever the chemistry, the most common cause of industrial floor coating failure is not the coating. It is moisture in the concrete.',
      'Concrete holds water. If moisture vapour is still migrating upward when the floor is sealed with an impermeable coating, pressure develops at the interface and the coating lifts — often in large sheets, often within months.',
      'The controls are unglamorous and non-negotiable: test the moisture content before application, allow adequate curing time for new slabs, use a moisture-tolerant primer where the reading is marginal, and mechanically prepare the surface by grinding or shot blasting rather than acid etching. Laitance and curing compound must be removed entirely.',
      'A floor that delaminates does not just cost the coating. It costs the downtime again, which was the expensive part the first time.',
      '## The comparison worth making',
      'Ask any flooring supplier for three numbers rather than one:',
      '1. Cost per square foot of the complete system, primer through topcoat',
      '2. Hours from final coat to foot traffic, and to full mechanical and chemical service',
      '3. Expected service life in your specific conditions, with a reference installation',
      'The second number, multiplied by the value of your daily output, is frequently larger than the first.',
    ],
  },
  'intumescent-fire-protection-dft-section-factor': {
    title: 'Intumescent Fire Protection: The DFT Is a Calculation, Not a Product Choice',
    date: '29 April 2026', readTime: '7 min read', category: 'Technical',
    image: '/img/heroes/hero-fire-protection.jpg',
    content: [
      'Most coating specifications state a dry film thickness taken from a product data sheet. Intumescent fire protection is the exception, and misunderstanding this is the most consequential error in the field, because the consequence is not premature corrosion. It is structural collapse during a fire.',
      '## What intumescent coatings do',
      'Structural steel does not burn, but it loses strength as it heats. By around 550°C, typical structural steel retains roughly half its ambient yield strength — which is broadly the point at which a loaded member can no longer carry its design load. This temperature is referred to as the critical or limiting steel temperature, and the precise figure depends on the member\'s utilisation.',
      'An intumescent coating looks like paint and behaves like paint until it reaches around 200–250°C. At that point it reacts: the film expands to many times its original thickness, forming a thick insulating char. That char slows heat transfer into the steel, delaying the point at which the member reaches its critical temperature — buying the time needed for occupants to escape and for the fire service to respond.',
      'The rating is expressed in minutes: 30, 60, 90, 120. It is a period of resistance, not a property of the coating alone.',
      '## Why the DFT cannot come off a data sheet',
      'The thickness required depends on how quickly the specific steel member heats up, and that varies enormously between members in the same building.',
      'This is captured by the **section factor**, written Hp/A or A/V — the ratio of the member\'s heated perimeter to its cross-sectional area. A light, slender section has a large surface area relative to its mass, so it heats rapidly and needs more insulation. A heavy column has a small section factor, heats slowly, and needs less.',
      'The required thickness is therefore a function of four things:',
      '1. The section factor of that specific member',
      '2. The required fire resistance period',
      '3. The critical steel temperature, which follows from the member\'s structural utilisation',
      '4. Whether the member is exposed on three sides or four',
      'The output is a **loading schedule** — a member-by-member table of required dry film thickness, derived from fire test data for that specific product, assessed to a standard such as EN 13381-8 or BS 476 Parts 20 and 21.',
      'On a real project, thicknesses across the schedule can vary by a factor of several between the lightest beam and the heaviest column. Applying one uniform thickness across the whole frame means some members are over-coated and wasteful, and others are under-protected and non-compliant.',
      '## The common site failures',
      '**Applying a single thickness throughout.** Faster, simpler, and wrong. Under-protected members do not announce themselves until a fire.',
      '**No wet film thickness monitoring during application.** Intumescent films are thick and applied in multiple passes. Without wet film checks during application, the dry film is a guess, and rectifying it afterwards is expensive.',
      '**Inadequate primer, or the wrong primer.** Intumescents must be applied over a compatible primer. A generic shop primer of unknown type is a real risk, and compatibility must be confirmed rather than assumed.',
      '**No topcoat where one is required.** Many intumescents are water-borne and vulnerable to moisture and UV. Exposed or semi-exposed conditions require a compatible sealer topcoat. Applying an incompatible topcoat can restrict expansion and compromise the entire system.',
      '**Damage during construction not repaired.** The frame is coated, then services are installed, brackets are welded, and the film is breached. Unrepaired damage is a gap in the protection.',
      '**No inspection record.** Fire protection is inspected by the authority having jurisdiction and by insurers. Absence of a documented thickness record per member is a compliance problem regardless of what was actually applied.',
      '## What a complete specification includes',
      'A proper passive fire protection package is not a line item naming a product. It contains:',
      'The required fire resistance period for each element, from the fire strategy',
      'The critical steel temperature adopted, with justification',
      'Section factors for every member, from the structural engineer',
      'The loading schedule of required DFT per member, from the coating manufacturer against their assessed test data',
      'Primer compatibility confirmation',
      'Topcoat requirement by exposure condition',
      'Inspection and recording procedure, including who signs off',
      'Damage repair procedure',
      '## Who does what',
      'This is deliberately a shared responsibility, and gaps appear where the handover is unclear. The fire engineer sets the required periods. The structural engineer supplies section factors and utilisations. The coating manufacturer produces the loading schedule from assessed test evidence. The applicator applies to that schedule and records what was achieved. The inspector verifies.',
      'If any one of those five is missing from a project, the fire protection is not documented, whatever is on the steel.',
      'Ask for the assessment report behind the loading schedule. A product with genuine third-party fire assessment will have one, covering the section factors and periods relevant to the project. It is the single most useful question to ask.',
    ],
  },
  'understanding-coating-systems-for-structural-steel': {
    title: 'Understanding Coating Systems for Structural Steel: A Complete Guide',
    date: '12 August 2026', readTime: '8 min read', category: 'Technical',
    image: '/img/app/industrial/ind-structural-spray.jpg',
    content: [
      'Structural steel is the backbone of modern infrastructure. Bridges, power plants, refineries, commercial buildings, and industrial facilities all depend on steel for structural integrity. But steel has one critical vulnerability — corrosion.',
      'When exposed to moisture, oxygen, and especially chlorides in coastal or industrial environments, steel corrodes. Without protection, a steel structure can lose significant cross-section within years, compromising its load-bearing capacity and safety.',
      '## How Multi-Coat Systems Work',
      'A protective coating system is not a single coat of paint. It is an engineered multi-layer system where each layer performs a specific function:',
      '**Primer** — The first coat applied directly to prepared steel. Zinc-rich primers provide sacrificial (cathodic) protection. Epoxy zinc phosphate primers provide inhibitive protection. The choice depends on the environment severity.',
      '**Intermediate Coat** — The barrier coat. Typically a high-build epoxy or epoxy MIO (micaceous iron oxide). This layer provides the bulk of the barrier protection, preventing moisture and oxygen from reaching the steel.',
      '**Topcoat** — The finishing coat. Aliphatic polyurethane for exterior exposure provides UV resistance, colour retention, and gloss retention. FEVE fluoropolymer for extreme weathering. Polysiloxane for long-term maintenance-free performance.',
      '## Selecting the Right System',
      'The correct system depends on several factors:',
      '**Environment** — classified by ISO 12944 from C1 (very low) to CX (extreme offshore). A rural building requires a different system than a coastal bridge or an offshore platform.',
      '**Design Life** — How long must the coating protect? 5 years (low), 15 years (medium), or 25+ years (high/very high)?',
      '**Surface Preparation** — The foundation of any coating system. Abrasive blast cleaning to Sa 2.5 is the gold standard for high-performance systems.',
      '**DFT (Dry Film Thickness)** — Each coat must achieve the specified thickness. Too thin reduces protection. Too thick can cause cracking.',
      '## Typical Systems by Environment',
      '**C3 General Industrial:** Epoxy Zinc Phosphate (50μm) → Epoxy MIO (100μm) → Aliphatic PU (50μm). Total: 200μm.',
      '**C4-C5 Coastal/Marine:** Inorganic Zinc Silicate (75μm) → High-Build Epoxy (150μm) → Aliphatic PU (50μm). Total: 275μm.',
      '**CX Offshore:** Inorganic Zinc Silicate (75μm) → Glass Flake Epoxy (200-500μm) → Aliphatic PU (50μm). Total: 325-625μm.',
      '## The Anupam Approach',
      'At Anupam Paints, we manufacture the complete range of structural steel coating systems — from zinc-rich primers to polyurethane topcoats. Our technical team can specify the right system for your project based on the actual environment, design life, and applicable standards.',
      'Contact our technical team for a system recommendation specific to your project.',
    ],
  },
  'why-surface-preparation-matters-more-than-paint-quality': {
    title: 'Why Surface Preparation Matters More Than Paint Quality',
    date: '5 August 2026', readTime: '6 min read', category: 'Technical',
    image: '/img/app/industrial/ind-zincrich.jpg',
    content: [
      'If you could invest in only one thing to improve coating performance, it should not be a more expensive paint. It should be better surface preparation.',
      'Industry data consistently shows that 60-80% of all premature coating failures are caused by inadequate surface preparation — not by the coating itself.',
      '## What Surface Preparation Does',
      'Surface preparation achieves three things:',
      '**Removes contaminants** — Oil, grease, salts, dust, and moisture on the surface prevent adhesion. Even invisible salt contamination from fingerprints can cause blistering.',
      '**Removes rust and mill scale** — Mill scale is the dark oxide layer formed during steel manufacturing. It looks protective but it is cathodic to steel and will cause underfilm corrosion.',
      '**Creates surface profile** — Blast cleaning creates tiny peaks and valleys (profile) that dramatically increase the surface area for mechanical adhesion.',
      '## Standards You Should Know',
      '**Sa 2.5 (Near-White Blast)** — The most commonly specified grade for high-performance systems. At least 95% of the surface is free from visible contaminants.',
      '**Sa 3 (White Metal Blast)** — Complete removal of all visible contaminants. Required for immersion service and some high-performance systems.',
      '**St 3 (Power Tool Cleaning)** — Acceptable for maintenance situations where blast cleaning is impractical. Not suitable for high-performance new construction.',
      '## The Bottom Line',
      'The best coating in the world will fail on a poorly prepared surface. And a well-prepared surface will make even a standard coating perform better than expected.',
      'Before specifying an expensive coating system, ensure your surface preparation specification is correct. It is the single most important factor in coating durability.',
    ],
  },
  'choosing-the-right-paint-for-your-home-interior': {
    title: 'Choosing the Right Paint for Your Home Interior',
    date: '28 July 2026', readTime: '5 min read', category: 'Home Painting',
    image: '/img/app/decorative/dec-living-premium.jpg',
    content: [
      'Selecting interior paint for your home involves more than picking a colour. The type of emulsion you choose determines how the walls look, how long the finish lasts, and how easy it is to maintain.',
      '## Luxury vs Premium vs Economy — What Is the Difference?',
      '**Luxury Emulsions (like Azura Pearl Glow)** — Use high-quality acrylic polymers and fine-ground pigments. Result: smoother finish, better coverage in fewer coats, superior washability (can withstand 10,000+ scrub cycles), stain resistance, and colour that does not fade. Cost: Rs.350-500/litre.',
      '**Premium Emulsions (like Asure CleanWalls)** — Good quality polymers with reliable coverage and washability (5,000+ scrub cycles). Excellent balance of performance and value. Cost: Rs.200-350/litre.',
      '**Economy Emulsions (like Atop Interior)** — Standard acrylic emulsions suitable for large-area painting where budget is primary. Decent coverage, basic washability. Cost: Rs.100-200/litre.',
      '## What Should You Choose?',
      '**Living room and bedrooms** — Luxury or premium. These are high-visibility rooms where finish quality, colour depth, and stain resistance matter.',
      '**Kitchen** — Luxury. Must withstand oil splashes, steam, and frequent cleaning.',
      '**Bathroom ceiling** — Premium with anti-fungal properties. Humidity resistance is critical.',
      '**Children\'s rooms** — Luxury washable. Kids will touch, draw, and splash. You need wipeable walls.',
      '**Rental property** — Economy with good primer. Functional and cost-effective.',
      '## The Primer Matters',
      'Never skip primer. A proper primer like Azura Damp Arrestor provides alkali resistance, improves adhesion, and ensures the topcoat colour appears true. Painting directly on bare plaster wastes paint and reduces durability.',
      'Visit an Anupam dealer near you or use our Paint Calculator to estimate quantities for your project.',
    ],
  },
  'rdso-approved-railway-coatings-what-makes-them-different': {
    title: 'RDSO Approved Railway Coatings: What Makes Them Different?',
    date: '20 July 2026', readTime: '7 min read', category: 'Railway',
    image: '/img/app/railway/rly-coach-painting.jpg',
    content: [
      'Indian Railways operates over 70,000 coaches across one of the world\'s largest rail networks. These coaches face extreme conditions — tropical UV, monsoon rains, temperature swings from 5°C to 50°C, stone chipping from ballast, chemical cleaning agents, and constant passenger use.',
      '## Why Railway Coatings Are Different',
      'A railway coach coating must simultaneously provide:',
      '**Corrosion protection** — The steel shell must be protected for 8-12 years between workshop repaints.',
      '**Appearance** — Gloss and colour must be retained despite years of UV exposure and chemical washing.',
      '**Fire safety** — EN 45545 HL3 compliance is increasingly required. The coating must not contribute to fire spread or toxic smoke.',
      '**Mechanical durability** — Resistance to stone impact from ballast, vibration, and regular cleaning.',
      '## The FEVE Advantage',
      'FEVE (Fluoroethylene Vinyl Ether) fluoropolymer topcoats offer the highest weatherability available in a liquid coating. Unlike conventional polyurethane, FEVE resins contain carbon-fluorine bonds that are virtually unbreakable by UV radiation.',
      'The result: gloss retention above 80% even after 10+ years of outdoor exposure, versus 40-50% for conventional PU.',
      '## Anupam\'s Railway Heritage',
      'Anupam Paints has been supplying Indian Railways for over three decades. Our ANUTHANE FEVE system has been tested for over 4000 hours in QUV accelerated weathering and meets EN 45545 HL3 R7 fire safety requirements.',
      'We supply coating systems to CLW, DMW, ICF, RCF, MCF, and multiple railway workshops across India.',
    ],
  },
  'waterproofing-your-terrace-common-mistakes-and-solutions': {
    title: 'Waterproofing Your Terrace: 5 Common Mistakes',
    date: '15 July 2026', readTime: '5 min read', category: 'Waterproofing',
    image: '/img/app/decorative/dec-roof-waterproof.jpg',
    content: [
      'Every monsoon, thousands of homeowners discover leaking terraces. The frustrating truth: most waterproofing failures are caused by application mistakes, not product failures.',
      '## Mistake 1: Not Finding the Water Source',
      'Before applying any waterproofing, you must identify WHERE water is entering. Is it through cracks? Pipe penetrations? Parapet junctions? Poor drainage causing ponding? Applying waterproofing over the wrong area wastes money.',
      '## Mistake 2: Skipping Crack Treatment',
      'Cracks in the RCC slab must be treated BEFORE applying the waterproofing membrane. Use a flexible crack filler like Arest Crack Filler to fill and bridge existing cracks. The membrane alone cannot bridge active structural cracks.',
      '## Mistake 3: Applying on a Wet Surface',
      'Waterproofing coatings need a dry substrate to adhere properly. Applying during rain or on a damp surface traps moisture underneath, causing blistering and delamination within months.',
      '## Mistake 4: Insufficient Thickness',
      'A thin coat is not waterproof. Follow the manufacturer\'s recommended coverage strictly. Multiple coats with proper drying between them create a continuous, pinhole-free membrane.',
      '## Mistake 5: Ignoring Details',
      'Most leaks occur at details — where the terrace meets the parapet wall, around pipe penetrations, at expansion joints, and at drainage outlets. These areas need reinforcement with fabric membrane embedded in the waterproofing system.',
      '## The Right System',
      'A proper terrace waterproofing system consists of: Surface cleaning → Crack filling → Primer → Base coat → Reinforcement at details → Second coat → UV-resistant topcoat.',
      'Anupam\'s Arest waterproofing range provides the complete system. Contact us for a site assessment.',
    ],
  },
};

export default function BlogPost() {
  const params = useParams();
  const slug = params.slug as string;
  const post = posts[slug];
  if (!post) return <div className="container-wide py-20 text-center"><h1 className="text-2xl font-bold">Post not found</h1><Link href="/blog" className="text-[var(--color-red)] mt-4 inline-block">Back to Blog</Link></div>;

  return (
    <>
      <section className="relative text-white overflow-hidden">
        <img src={post.image} alt="" className="absolute inset-0 w-full h-full object-cover" />
        <div className="absolute inset-0 bg-[var(--color-navy)]/75" />
        <div className="container-wide py-16 md:py-24 relative z-10">
          <Link href="/blog" className="text-white/50 text-sm flex items-center gap-1 mb-4 hover:text-white transition"><ArrowLeft size={14} /> Back to Blog</Link>
          <span className="text-xs font-semibold uppercase tracking-wider" style={{color:'var(--color-red)'}}>{post.category}</span>
          <h1 className="text-page-title text-white mt-2 mb-4">{post.title}</h1>
          <div className="flex items-center gap-4 text-sm text-white/50">
            <span className="flex items-center gap-1"><Calendar size={14} /> {post.date}</span>
            <span className="flex items-center gap-1"><Clock size={14} /> {post.readTime}</span>
          </div>
        </div>
      </section>
      <section className="section-padding bg-white">
        <div className="container-wide max-w-3xl">
          <div className="space-y-4">
            {post.content.map((para: string, i: number) => {
              if (para.startsWith('## ')) return <h2 key={i} className="text-xl font-bold text-[var(--color-navy)] mt-8 mb-2">{para.replace('## ', '')}</h2>;
              if (para.startsWith('**') && para.endsWith('**')) return <h3 key={i} className="font-bold text-[var(--color-navy)] mt-4">{para.replace(/\*\*/g, '')}</h3>;
              const formatted = para.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
              return <p key={i} className="text-[var(--color-steel)] leading-relaxed" dangerouslySetInnerHTML={{__html: formatted}} />;
            })}
          </div>
          <div className="mt-12 pt-8" style={{borderTop:'1px solid var(--color-border)'}}>
            <h3 className="font-bold text-[var(--color-navy)] mb-3">Need Technical Assistance?</h3>
            <p className="text-sm text-[var(--color-steel)] mb-4">Our team can help you select the right coating system for your specific application.</p>
            <div className="flex gap-3">
              <Link href="/contact" className="bg-[var(--color-red)] text-white font-semibold px-5 py-2.5 text-sm" style={{borderRadius:'var(--radius-md)'}}>Contact Technical Team</Link>
              <Link href="/technical-library" className="border border-[var(--color-border)] text-[var(--color-navy)] font-semibold px-5 py-2.5 text-sm" style={{borderRadius:'var(--radius-md)'}}>Browse TDS Library</Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}